from simvue_fds.connector import FDSRun
import pathlib
import f90nml
import requests
from simvue.config.user import SimvueConfiguration
import pandas
import numpy
def parse_line_data(run, scenario_name):
        # Load input file as data (normally done by Multiparser)
        nml = f90nml.read(pathlib.Path(__file__).parent.joinpath("example_data", "line_devices", f"{scenario_name}.fds")).todict()
        run._input_dict = {k: v for k, v in nml.items() if v}
        
        # Add this which is typically added in launch()
        run._line_var_coords = {}
        
        # Generate mapping
        run._map_line_var_coords()
        
def extract_line_metrics(run, scenario_name):
    meta, data = run._line_parser(str(pathlib.Path(__file__).parent.joinpath("example_data", "line_devices", f"{scenario_name}.csv")))
    # Add this which is typically added by multiparser
    meta["file_name"] = f"{scenario_name}.csv"
    run._line_callback(data, meta)
    
def get_line_metrics(run_id, scenario_name, metric):
    # Check slice uploaded as 3D metric
    _user_config: SimvueConfiguration = SimvueConfiguration.fetch()
    response = requests.get(
        url=f"{_user_config.server.url}/runs/{run_id}/metrics/{metric}/values?step=0",
        headers={
            "Authorization": f"Bearer {_user_config.server.token.get_secret_value()}",
            "User-Agent": "Simvue Python client",
            "Accept-Encoding": "gzip",
        }
    )
    assert response.status_code == 200
    data = response.json().get("array", [])
    assert len(data) == 20
    
    return data

def compare_grid_metrics(scenario_name, metric_name, metric_data, axes_name, axes_data):
    # Load CSV file
    df = pandas.read_csv(str(pathlib.Path(__file__).parent.joinpath("example_data", "line_devices", f"{scenario_name}.csv")), skiprows=1)

    # Check axes ticks data generated by run matches that in CSV file
    numpy.testing.assert_allclose(axes_data, df[axes_name].tolist())
    
    # Check metric data retrieved from run matches that in CSV file
    numpy.testing.assert_allclose(metric_data, df[metric_name].tolist())
    

def test_single_devc_xb(folder_setup):
    scenario_name = "single_devc_xb"
    with FDSRun() as run:
        run._dispatch_mode = "direct"
        run.init(name=scenario_name, folder=folder_setup)
        parse_line_data(run, scenario_name)
        
        # Check device ID has been mapped to correct axis label
        assert run._line_var_coords["temp_line"]["label"] == "y"
        
        extract_line_metrics(run, scenario_name)
        
        metric = get_line_metrics(run.id, scenario_name, "temp_line")
        
        compare_grid_metrics(scenario_name, "temp_line", metric, "temp_line-y", run._line_var_coords["temp_line"]["ticks"])
        
def test_single_devc_xbp(folder_setup):
    scenario_name = "single_devc_xbp"
    with FDSRun() as run:
        run._dispatch_mode = "direct"
        run.init(name=scenario_name, folder=folder_setup)
        
        parse_line_data(run, scenario_name)
        
        # Check device ID has been mapped to correct axis label
        assert run._line_var_coords["temp_line"]["label"] == "y"
        
        extract_line_metrics(run, scenario_name)
        
        metric = get_line_metrics(run.id, scenario_name, "temp_line")
        
        compare_grid_metrics(scenario_name, "temp_line", metric, "temp_line-y", run._line_var_coords["temp_line"]["ticks"])
        
def test_single_devc_coord_id():
    scenario_name = "single_devc_coord_id"
    with FDSRun() as run:
        parse_line_data(run, scenario_name)
        
        # Check device ID has been mapped to correct axis label (user specified: y_coords)
        assert run._line_var_coords["temp_line"]["label"] == "y_coords"
        
        
def test_single_devc_multi_dimension():
    scenario_name = "single_devc_multi_dimension"
    with FDSRun() as run:
        parse_line_data(run, scenario_name)
        
        # Only supports 1D line devices for now - so this should not be in mapping, indicating that this device should be skipped when adding metrics
        assert not run._line_var_coords.get("temp_line")
        
def test_single_devc_no_id():
    scenario_name = "single_devc_no_id"
    with FDSRun() as run:
        parse_line_data(run, scenario_name)
        
        # Should skip devices which have no ID provided
        assert run._line_var_coords == {}
        
def test_multi_devc():
    scenario_name = "multi_devc"
    with FDSRun() as run:
        parse_line_data(run, scenario_name)
        
        # Check both devices mapped to their default values
        assert run._line_var_coords["temp_line_y"]["label"] == "y"
        assert run._line_var_coords["temp_line_x"]["label"] == "x"
        
def test_multi_devc_coord_id():
    scenario_name = "multi_devc_coord_id"
    with FDSRun() as run:
        parse_line_data(run, scenario_name)
        
        # Check both devices mapped to their user specified values
        assert run._line_var_coords["temp_line_y"]["label"] == "y_coords"
        assert run._line_var_coords["temp_line_x"]["label"] == "x_coords"
        
def test_multi_devc_hide_coords():
    scenario_name = "multi_devc_hide_coords"
    with FDSRun() as run:
        parse_line_data(run, scenario_name)
        
        # Check both devices are using default coord name
        assert run._line_var_coords["temp_line_y"]["label"] == "y"
        assert run._line_var_coords["velocity_line_y"]["label"] == "y"
        
def test_multi_devc_coord_id_hide_coords():
    scenario_name = "multi_devc_coord_id_hide_coords"
    with FDSRun() as run:
        parse_line_data(run, scenario_name)
        
        # Check both devices are using user specified coord name from first defined device
        assert run._line_var_coords["temp_line_y"]["label"] == "y_coords"
        assert run._line_var_coords["velocity_line_y"]["label"] == "y_coords"
        
def test_multi_devc_multi_hide_coords():
    scenario_name = "multi_devc_multi_hide_coords"
    with FDSRun() as run:
        parse_line_data(run, scenario_name)
        
        # Check first two devices are using user specified 'y_coords'
        assert run._line_var_coords["temp_line_y"]["label"] == "y_coords"
        assert run._line_var_coords["velocity_line_y"]["label"] == "y_coords"
        
        # Check second two devices are using default z coords
        assert run._line_var_coords["temp_line_z"]["label"] == "z"
        assert run._line_var_coords["velocity_line_z"]["label"] == "z"
        
def test_multi_devc_hide_coords_invalid():
    scenario_name = "multi_devc_hide_coords_invalid"
    with FDSRun() as run:
        parse_line_data(run, scenario_name)
        
        # Check first two devices are using user specified 'y_coords'
        assert run._line_var_coords["temp_line_y"]["label"] == "y_coords"
        assert run._line_var_coords["velocity_line_y"]["label"] == "y_coords"
        
        # Check last two devices are using default z coords
        assert run._line_var_coords["temp_line_z"]["label"] == "z"
        assert run._line_var_coords["velocity_line_z"]["label"] == "z"
        
        # Check middle two devices are not added, since they have 2D axes which we do not support
        assert not run._line_var_coords.get("temp_line_multi_dim")
        assert not run._line_var_coords.get("velocity_line_multi_dim")
        
def test_multi_point_and_line_devc():
    scenario_name = "multi_point_and_line_devc"
    with FDSRun() as run:
        parse_line_data(run, scenario_name)
        
        # Check point DEVC devices are not in mapping
        assert not run._line_var_coords.get("velocity_point")
        assert not run._line_var_coords.get("temperature_point")
        assert not run._line_var_coords.get("visibility_point")
        
        # Check line DEVC devices are correctly using user specified 'y_coords'
        assert run._line_var_coords["temp_line_y"]["label"] == "y_coords"
        assert run._line_var_coords["velocity_line_y"]["label"] == "y_coords"