name: Simvue Nightlies (Ubuntu)
on:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  FDS:
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    container:
      image: openbcl/fds:6.9.1
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"
      - name: Install poetry
        run: python3 -m pip install poetry
      - name: Install dependencies and run tests
        run: |
          apt-get update && apt-get install -y libgl1 libglib2.0-0 libsm6 libxrender1 libxext6
          export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
          export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
          poetry install --all-extras
          poetry run pytest tests/integration/test_fds.py

